import { expect, snap, test, visit } from '../fixtures'
import { ready } from '../dashboard/ready'

test('ads', async ({ page }) => {
  await visit(page, '/ads')
  await expect(page.getByTestId('subnav-all')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('sub-nav').locator('a')).toHaveCount(4)
  await expect(page.getByTestId('ads-company').first()).toHaveAttribute('data-state', 'ready', { timeout: 20_000 })
  const cards = page.getByTestId('ad-card')
  await expect(cards.first()).toBeVisible()
  await expect(cards.locator('a').first()).toHaveAttribute('target', '_blank')
  await expect(cards.locator('a:not([target="_blank"])')).toHaveCount(0)
  const media = page.getByTestId('ad-media').first()
  await expect(media).toBeVisible()
  await expect(media).toHaveAttribute('target', '_blank')
  await expect(media).toHaveAttribute('href', /^https:\/\//)
  await ready(page)
  await snap(page, 'spy-ads')
  await visit(page, '/ads/google')
  await expect(page.getByTestId('subnav-google')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('ad-media').first()).toHaveAttribute('href', /^https:\/\/displayads-formats/)
  await ready(page)
  await snap(page, 'spy-ads-google')
  await visit(page, '/ads/linkedin')
  await expect(page.getByTestId('subnav-linkedin')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('ad-card').first()).toBeVisible()
  const landing = page.getByTestId('ad-landing').first()
  await expect(landing).toBeVisible()
  await expect(landing).toHaveAttribute('target', '_blank')
  await ready(page)
  await snap(page, 'spy-ads-linkedin')
  await visit(page, '/ads/tiktok')
  await expect(page.getByTestId('subnav-tiktok')).toHaveAttribute('aria-current', 'page')
  await expect(page.getByTestId('ad-card').first()).toBeVisible()
  const tiktokMedia = page.getByTestId('ad-media').first()
  await expect(tiktokMedia).toBeVisible()
  await expect(tiktokMedia).toHaveAttribute('target', '_blank')
  await ready(page)
  await snap(page, 'spy-ads-tiktok')
})
